server:
  port: 1111

spring:
  datasource:
    url: jdbc:mysql://122.51.154.61:3306/zhangJiong?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zj.entity


#showSql
logging:
  level:
    com:
      example:
        mapper : debug
